# Generated by Django 5.2.14 on 2026-05-26 18:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('demandes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Releve',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fichier_pdf', models.FileField(upload_to='releves/')),
                ('date_generation', models.DateTimeField(auto_now_add=True)),
                ('demande', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='releve', to='demandes.demande')),
            ],
            options={
                'verbose_name': 'Relevé',
                'verbose_name_plural': 'Relevés',
            },
        ),
    ]
