# Generated by Django 5.2.14 on 2026-05-29 10:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportNotes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fichier', models.FileField(upload_to='imports/')),
                ('filiere', models.CharField(max_length=10)),
                ('session', models.CharField(max_length=50)),
                ('annee', models.CharField(max_length=10)),
                ('date_depot', models.DateTimeField(auto_now_add=True)),
                ('statut', models.CharField(choices=[('depose', 'Déposé par Chef Département'), ('valide_dga', 'Validé par DGA'), ('valide_dg', 'Validé par DG — Actif'), ('rejete', 'Rejeté')], default='depose', max_length=20)),
                ('date_validation_dga', models.DateTimeField(blank=True, null=True)),
                ('date_validation_dg', models.DateTimeField(blank=True, null=True)),
                ('nb_notes_importees', models.IntegerField(default=0)),
                ('commentaire', models.TextField(blank=True, null=True)),
                ('depose_par', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='imports_deposes', to=settings.AUTH_USER_MODEL)),
                ('valide_par_dg', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='imports_valides_dg', to=settings.AUTH_USER_MODEL)),
                ('valide_par_dga', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='imports_valides_dga', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Import de Notes',
            },
        ),
    ]
