# Generated by Django 5.2.14 on 2026-06-04 13:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0002_importnotes'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='import_source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lignes_notes', to='notes.importnotes'),
        ),
    ]
