# Generated by Django 6.0.6 on 2026-06-10 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("demandes", "0002_alter_demande_statut"),
    ]

    operations = [
        migrations.AlterField(
            model_name="demande",
            name="statut",
            field=models.CharField(
                choices=[
                    ("en_attente", "En attente"),
                    ("validee", "Validée"),
                    ("rejetee", "Rejetée"),
                ],
                default="en_attente",
                max_length=20,
            ),
        ),
    ]
