# Generated by Django 5.2.14 on 2026-06-02 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etudiants', '0002_profiladmin'),
    ]

    operations = [
        migrations.AddField(
            model_name='etudiant',
            name='est_valide',
            field=models.BooleanField(default=False),
        ),
    ]
