# Generated by Django 6.0.6 on 2026-06-04 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("etudiants", "0003_etudiant_est_valide"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profiladmin",
            name="role",
            field=models.CharField(
                choices=[
                    ("admin", "Administrateur Système"),
                    ("dg", "Directeur Général"),
                    ("dga", "Directeur Général Adjoint"),
                    ("chef_ntic", "Chef de Département NTIC"),
                    ("chef_dl", "Chef de Département DL"),
                ],
                max_length=20,
            ),
        ),
    ]
