# Generated by Django 6.0.6 on 2026-06-05 21:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("etudiants", "0005_add_valide_par_chef"),
    ]

    operations = [
        migrations.AlterField(
            model_name="etudiant",
            name="departement",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="etudiants",
                to="etudiants.departement",
            ),
        ),
        migrations.AlterField(
            model_name="etudiant",
            name="est_valide",
            field=models.BooleanField(default=False, verbose_name="Compte actif"),
        ),
        migrations.AlterField(
            model_name="etudiant",
            name="niveau",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="etudiants",
                to="etudiants.niveau",
            ),
        ),
    ]
